name: "案件依頼チケット"
description: "案件依頼のチケットです"
body:
  - type: textarea
    id: content
    attributes:
      label: "案件依頼"
      description: "どのような事項を実施するかを記載"
      placeholder: |
        〇〇の処理を作成する
    validations:
      required: true
  - type: textarea
    id: howTo
    attributes:
      label: "どのように"
      description: |
        どのような手順で作成するか
      value: |
        1. 〇〇の処理を作成
        2. 〇〇のコンポーネントを作成
        3. ページを作成
  - type: textarea
    id: issue
    attributes:
      label: "関連issue"
      description: |
        関連するissueの番号を表記してください
