# This is a basic workflow to help you get started with Actions

name: query_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find SQL files with invalid number
        id: find_files
        run: |
          find sql -name 'sample_code' -print0 | xargs -0 grep -Hn 'number [^0-9]{13}' > invalid_numbers.txt
      - name: Check if there are invalid files
        if: steps.find_files.outputs.files_found == 'true'
        run: |
          if [ -s invalid_numbers.txt ]; then
            echo "::error file=invalid_numbers.txt,line=1,col=1::SQL files with invalid number found. Check invalid_numbers.txt for details."
          fi
