# This is a basic workflow to help you get started with Actions

name: query_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_number_length:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check SQL file
        run: |
          # SQLファイルのパスを指定
          sql_file="sample_code"

          # SQLファイルを読み込み、各行を処理
          while IFS= read -r line; do
            # numberカラムの値を抽出 
            echo $line
            if: $line =~ number='([0-9]+)'
              number=${BASH_REMATCH[1]}
              echo "hit"
              # 桁数チェック
              if: ${#number} -ne 13
                echo "Error: Number の値は 13 桁である必要があります in line: $line"
                exit 1
          done < "$sql_file"
